- quickstart.mdx
Our CLI falls flat on its face when attempting to integrate an existing Next.js app. For this reason I'm removing any reference to that in our docs, app, and am going to remove the functionality from the CLI.
> fix: CLI can't integrate existing Next.js apps

- developer/app-router/installation.mdx
- developer/app-router/localization.mdx
- developer/concepts.mdx
- developer/guides/environments.mdx
- developer/pages-router/installation.mdx
- developer/pages-router/localization.mdx
- developer/quickstart.mdx
- developer/reference/client/constructor.mdx
- developer/reference/client/get-page-snapshot.mdx
- developer/reference/client/get-pages.mdx
- developer/reference/client/get-site-version.mdx
- developer/reference/client/get-sitemap.mdx
- developer/reference/components/react-runtime-provider.mdx
- developer/reference/controls/list.mdx
- developer/reference/controls/shape.mdx
- developer/reference/runtime/register-component.mdx
- developer/upgrading/0.13.0.mdx
- developer/upgrading/0.14.0.mdx
- developer/upgrading/0.15.0.mdx
- developer/upgrading/0.18.0.mdx
- developer/upgrading/0.19.0.mdx
- product/component/property-controls/backgrounds.mdx
- product/page/metadata.mdx
- product/quickstart.mdx
- snippets/naming-conventions.mdx
You can easily search for broken links by running the command:
mintlify broken-links
There are still 5 broken links because the CLI has a bug for a link that has dot ".":
https://github.com/mintlify/docs/issues/178#issuecomment-2191014928
> fix: broken links

- developer/guides/troubleshooting.mdx
The original internal blog post referenced here causes an obscure bug in Makeswift (relatively low priority for now).
Instead, we are now referring to the Next.js guide to use enable HTTPS while running locally which does work with Makeswift.
Both were tested and confirmed by @migueloller
> Update Troubleshooting Mixed Content in Safari

- .prettierrc
Adding the prettier configuration file will prevent local prettier configurations from overriding team decisions. This file includes settings that match the existing format of docs.
> Added prettierrc for consistent styling

- mint.json
Added redirect from outdated url for rich-text docs `https://www.makeswift.com/docs/controls/rich-text` (referenced in screenshot)
> Added redirect for rich-text control docs

- developer/quickstart.mdx
Developer quickstart was using h1 headings that have been changed to h2
> Developer Quickstart - h1 to h2

- developer/app-router/installation.mdx
Move instructions to delete the root page component outside of a callout. Added a callout to clarify the use case of non-optional route and how to support a hard-coded home page.
> Update: callout for optional catch-all route

- product/publishing.mdx
Video upload didn't appear to work with Mintlify, so we are removing the video for now until we figure out why.
> fix: hide scheduled publishes video

- developer/reference/components/react-runtime-provider.mdx
Update example section to include more context around App and Pages Router examples.
> docs: update snippets for previewMode in ReactRuntimeProvider

- developer/reference/components/makeswift-component.mdx
- developer/reference/makeswift-api-handler.mdx
- developer/upgrading/0.23.0.mdx
- mint.json
- snippets/reference/fonts.mdx
- added new guide
- moved upgrade guides to nested section under `guides` in side navbar
- updated `MakeswiftApiHandler` props to reflect new changes
> Add Upgrade Guide for 0.23

- snippets/app-router/api-handler.mdx
- snippets/pages-router/api-handler.mdx
The API route needs a components import, otherwise it won't know about any of the custom components and won't be able to introspect them/replace the resources.
> fix: add components import to the API route snippets

- developer/guides/deploying/docker.mdx
- developer/guides/deploying/overview.mdx
- mint.json
Added a doc for deploying using Docker. Primarily, this links to the existing Vercel documentation with two callouts on runtime version and environment variables.
> Add docker deploy Doc

- developer/guides/deploying/docker.mdx
Reflect [`FORCE_HTTP` -> `MAKESWIFT_DRAFT_MODE_PROXY_FORCE_HTTP` rename](https://github.com/makeswift/makeswift/releases/tag/%40makeswift%2Fruntime%400.23.4), add more details about the flag based on @migueloller's suggestion [here](https://makeswifthq.slack.com/archives/C06GE9DBY78/p1738679678027999?thread_ts=1738630500.101029&cid=C06GE9DBY78).
> docs: reflect `FORCE_HTTP` rename, add more detail

- developer/messages/manifest-unreachable.mdx
The {" "} was causing the issue of TypeError: Cannot read properties of undefined (reading 'title')
In this commit, I also format the indentation.
All other message docs look fine.
Before
After
> fix: unreachable manifest doc

- developer/upgrading/0.23.0.mdx
- mint.json
- add diffs for snippet examples
- add callout for pages router that requires `previewData` to be returned from `getStaticProps`
> 0.23 Upgrade Guide Code Snippets

- developer/guides/how-to/setting-cookies.mdx
- mint.json
- product/troubleshooting/cookies.mdx
Introduce documentation for modifying cookies so that they can be set within the builder. Includes docs for product users (modifying browser settings) and developers (modifying cookie attributes).
> feat: add developer and product docs for cookies

- developer/app-router/installation.mdx
- developer/pages-router/installation.mdx
Addressing https://github.com/makeswift/makeswift/discussions/965#discussioncomment-12501601
This was a breaking change in https://docs.makeswift.com/developer/upgrading/0.21.0#pages-router%E2%80%99s-custom-document, but we didn't fully reflect it in the guide.
> fix: Pages Router `Document` import paths, improve flow

- developer/reference/makeswift-api-handler.mdx
- snippets/reference/on-publish.mdx
This PR adds `events.onPublish` for `MakeswiftApiHandler`.
https://makeswift-sasha-eng-8259-add-onpblish-event-to-docs.mintlify.app/developer/reference/makeswift-api-handler
> docs: add events.onPublish for MakeswiftApiHandler

- developer/reference/client/get-component-snapshot.mdx
- developer/reference/client/get-page-snapshot.mdx
Update client `getSnapshot` methods to include docs for the `allowLocaleFallback` param. Also adds changelogs to both methods.
> fix: update snapshot methods to include allowLocaleFallback

- developer/guides/troubleshooting/builder-is-not-loading.mdx
- mint.json
I am planning to put more content under `Developer`/`Troubleshooting` and wanted it to be a group rather than a page.
> refactor: make Developer/Troubleshooting a group

- snippets/components/icon-list.mdx
- use 20 by 20 for each icon 
- use consistent gray color
> Consistent size and color for component icons
